remote_theme: "mmistakes/minimal-mistakes"
title: "CBAS Research"
name: "Sergio Vargas"
repository: "sevragorgia/Research"
header:
  teaser: /images/CBAS.jpg
search: true
search_full_content: true

# Site Author
author:
  name             : "Sergio Vargas"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Biologist interested in sponges, their bacteria and the interactions between them"  
  location         : "Munich, Germany"
  email            :
  uri              : "https://sevragorgia.github.io/Research
  github           : "sevragorgia"
  linkedin         : "sergio-vargas-36961653"
  twitter          : "sevragorgia"
  
