remote_theme: "mmistakes/minimal-mistakes"
title: "CBAS Research"
name: "Sergio Vargas"
repository: "sevragorgia/Research"
header:
  teaser: #/images/CBAS.jpg
search: true
search_full_content: true

# Site Author
author:
  name             : "Sergio Vargas"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Biologist interested on the interactions between sponges and their bacteria"
  location         : "Munich, Germany"
  email            : #
  uri              : "https://sevragorgia.github.io/Research"
  github           : "sevragorgia"
  linkedin         : "sergio-vargas-36961653"
  twitter          : "sevragorgia"
  
# Social Sharing
twitter:
  username               : sevragorgia
og_image                 : # Open Graph/Twitter default site image

social:
  type: #
  name: #
  links:
    - "https://twitter.com/sevragorgia"

# Reading Files
include:
  - _pages
  - _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single


