remote_theme: "mmistakes/minimal-mistakes"
title: "CBAS Research"
name: "Sergio Vargas"
repository: "sevragorgia/Research"
header:
  teaser: #/images/CBAS.jpg
search: true
search_full_content: true

# Site Author
author:
  name             : "Sergio Vargas"
  avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "Biologist interested on the interactions between sponges and their bacteria"
  location         : "Munich, Germany"
  email            : #
  uri              : "https://sevragorgia.github.io/Research"
  github           : "sevragorgia"
  linkedin         : "sergio-vargas-36961653"
  twitter          : "sevragorgia"
  
# Social Sharing
twitter:
  username               : sevragorgia
og_image                 : # Open Graph/Twitter default site image

social:
  type: #
  name: #
  links:
    - "https://twitter.com/sevragorgia"
