remote_theme: "mmistakes/minimal-mistakes"
title: "sevra's research"
name: "Sergio Vargas"
repository: "sevragorgia/Research"
search: true
search_full_content: true
author_profile: true
url: "https://sevragorgia.github.io"
baseurl: "/Research"
share: true
words_per_minute: 200
locale: "en-US"

# Site Author
author:
  name             : "Sergio Vargas"
  bio              : "Biologist interested on the interactions between sponges and their bacteria"
  location         : "Munich, Germany"
  uri              : "https://scholar.google.com/citations?user=OAcpy4EAAAAJ&hl=en"
  #uri              : "https://sevragorgia.github.io/Research"
  github           : "sevragorgia"
  linkedin         : "sergio-vargas-36961653"
  twitter          : "sevragorgia"
  
# Social Sharing
twitter:
  username               : sevragorgia
og_image                 : /assets/images/OGCBAS.jpg

# Reading Files
include:
  - _pages
  #- _posts
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  - /docs # ignore Minimal Mistakes /docs
  - /test # ignore Minimal Mistakes /test
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      share: false
      comments: false
  # _scrpits
  #- scope:
   #   path: ""
    #  type: scripts
    #values:
     # layout: single
      #author_profile: true
     # share: true
      #comments: false


category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
envs: development
